version: '3.1'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=reviews
            - POSTGRES_USER=reviews
            - POSTGRES_PASSWORD=reviews
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    web:
        build: .
        command: tail -f /dev/null #python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
