# Generated by Django 3.0.7 on 2020-07-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('sampled_date', models.DateTimeField(verbose_name='date sampled')),
            ],
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_text', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('sampled_date', models.DateTimeField(verbose_name='date sampled')),
                ('opinions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_reviews.Reviews')),
            ],
        ),
    ]
