# Generated by Django 3.0.7 on 2020-07-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_reviews', '0002_auto_20200702_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opinions',
            new_name='Opinion',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
