# Generated by Django 3.0.7 on 2020-07-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_reviews', '0003_auto_20200702_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='opinions',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='ml_reviews.Review'),
        ),
    ]
